# Site settings
title: WCC Signups
email: evoris@wccstl.org
url: http://www.wccstl.org
description: "Sign up to get involved at Wildwood Christian Church. Join a small group today!"
vision: "Connecting our distracted community into a life focused on Jesus."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #turquoise,about
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #footer-above,navbar
  secondary-dark: 233140 #footer-below

# Footer settings
footer:
  copyright: Wildwood Christian Church
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:office@wccstl.org
  - title: facebook
    url: https://www.facebook.com/wccstl
  - title: music
    url: https://itunes.apple.com/us/podcast/wildwood-christian-church/id761424836

# Postal address (add as many lines as necessary)
address:
  - line: 16717 Manchester Rd.
  - line: Wildwood, MO 63040

# Build settings
markdown: kramdown
permalink: pretty
